# Data configuration
data:
  tickers: ['AAPL', 'MSFT', 'AMZN', 'TSLA', '^GSPC', '^DJI', '^IXIC']
  start_date: '2015-01-01'
  end_date: '2024-12-31'
  fred_indicators: ['VIXCLS', 'GDP', 'T10YIE']
  
# Feature engineering
features:
  technical_indicators:
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    bb_period: 20
    bb_std: 2
    sma_short: 50
    sma_long: 200
  
# Target configuration  
targets:
  - name: 'return_1d'
    type: 'regression'
    horizon: 1
  - name: 'direction_1d'
    type: 'classification'
    horizon: 1
  - name: 'return_5d'
    type: 'regression'
    horizon: 5

# Model configuration
models:
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

  decision_tree:
    max_depth: 10
    min_samples_split: 20
    min_samples_leaf: 10

  xgboost:
    n_estimators: 1000
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    early_stopping_rounds: 50

  cnn:
    epochs: 50
    batch_size: 32
    window_size: 20

  lstm:
    epochs: 50
    batch_size: 32
    window_size: 20
    hidden_units: 64
    n_layers: 2
    dropout_rate: 0.2

  gru:
    epochs: 50
    batch_size: 32
    window_size: 20
    hidden_units: 64
    n_layers: 2
    dropout_rate: 0.2

  arima:
    p: 5  # AR order
    d: 1  # Differencing order
    q: 1  # MA order
    seasonal: false
  
# Paths
paths:
  data_dir: 'data/raw/'
  processed_dir: 'data/processed/'
  models_dir: 'models/saved/'
  plots_dir: 'plots/'